### ISSUE TITLE
Can I download the theme and use it for free?

### ISSUE THREAD

**Issue by jokersie** [maithemewp/mai-lifestyle-pro#1]
Can I download the theme and use it for free? I found it can be downloaded via Github, so why should I buy, what are the benefits of buying?

**Comment by JiveDig** [comment]
Legally, all WordPress things open source, and we keep this ‘open’ so other developers can see our code and we build trust, as well as allow them to offer bug fixes, reports, and feature requests. 

That being said... ethically, it would not be okay, since it is our business and our livelihoods to sell themes/code.
